### ISSUE TITLE
Add support for multi-document yaml files

### ISSUE THREAD

**Issue by vkhromov** [fiddyspence/puppet-hash_file#6]
Some applications require several documents to be stored inside a single `yaml` file, i.e. [Kubernetes nginx ingress controller deploy file](https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml):
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
...
```

At the moment `hash_file` doesn't seem to be able to generate such kind of `yaml` files, i.e. for
```puppet
hash_file { '/somewhere/something.yaml':
    value => [
        {
            'kind' => 'Namespace',
        },
        {
            'kind' => 'ConfigMap',
        },
    ],
    provider => 'yaml',
}
```
it outputs only a single document `yaml` file with only the first element from the list
```yaml
---
kind: Namespace
```
not the whole list in a multidoc `yaml` file as expected
```yaml
---
kind: Namespace
---
kind: ConfigMap
```
While the expected result could be archived by some magic involved generating every `yaml` document in its own file by several calls to `hash_file`, then `cat`'ing the resulted `yaml` files into a single multidoc `yaml` file, while at the same time adding proper dependencies between all these moving parts, that would be much more convenient to be able to generate such multi-document `yaml` files in a single call to `hash_file`.

One of possible solutions is to add a new `yaml_multidoc` provider which will generate such multi-document `yaml` files:
```puppet
hash_file { '/somewhere/something.yaml':
    value => [
        {
            'kind' => 'Namespace',
        },
        {
            'kind' => 'ConfigMap',
        },
    ],
    provider => 'yaml_multidoc',
}
```
